### PR TITLE
autogen script

### PR DESCRIPTION
**Pull request by manasdk**
- Autogen script capable of generating actions by reading from cliff based argument parsing
- Some assumption made with relation to python-openstackclient so unlikely to work with
  and and all cliff based apps.
- README for usage

TODO
- [x] Check-in autogenerated actions
- [x] Use json as default format
- [x] skip column of the format group
- [x] update base.py and wrapper.py to work with new action schema

### CODE REVIEW

**Comment by manasdk** [comment]
There are 158 actions. we may have to come up with a better organization mechanism. Thoughts?

**Comment by jfryman** [comment]
A better organization method? Like, how me manage folders?

It's always driven me a bit nuts that it's configuration over convention in this matter. I'd really love to see folder subtrees that match the namespace. 

aggregate.host.add == Actions/aggregate/host/add.yaml

**Comment by manasdk** [comment]
> aggregate.host.add == Actions/aggregate/host/add.yaml

Yes. That is possible to do but requires changes to StackStorm platform. Very java like :P

Just to be clear not doing this right now.

**Comment by manasdk** [comment]
:boom: 

SUCCESS!! Merging in to master!

**Pull request merged**
